# Descarga Catálogos, crossmatch y creación de tablas.  

Enlaces relacionados y de interés:  

https://astroquery.readthedocs.io/en/latest/simbad/simbad.html

In [254]:
import numpy as np
import astropy.units as u
from astropy.table import Table, QTable
from astropy.coordinates import SkyCoord
import matplotlib.pyplot as plt


from astroquery.simbad import Simbad
from astropy.coordinates import Angle

from  astroquery.gaia import Gaia
import pandas as pd

# SAIKIA

In [255]:
from astroquery.vizier import Vizier
Vizier.ROW_LIMIT=-1

In [256]:
catalog_list = Vizier.find_catalogs('Saikia')
['{};{}'.format(k,v.description) for k,v in catalog_list.items()]

["J/ApJ/905/87;LCO i'band LC of SAX J1808.4-3658 (Baglio+, 2020)",
 'J/ApJS/238/9;Catalog of giant radio sources known to date (Kuzmicz+, 2018)',
 'J/A+A/555/A4;Radio polarimetry of CSS sources (Mantovani+ 2013)',
 'J/A+A/616/A108;Cool stars chromospheric activity catalog (Boro Saikia+, 2018)',
 'J/A+A/642/A153;SAGAN. I. New sample & multi-wavelength studies (Dabhade+, 2020)',
 'J/A+A/660/A59;SAGAN III. New insights into giant radio quasars (Mahato+, 2022)',
 'J/MNRAS/392/1403;GMRT radios sources around J0916+6348 field (Sirothia+, 2009)',
 'J/MNRAS/393/1275;STAGES master catalog (Gray+, 2009)',
 'J/MNRAS/395/269;ELAIS-N1 field 325MHz observations (Sirothia+, 2009)',
 'J/MNRAS/406/2578;Galaxies near S1189 (Mao+, 2010)',
 'J/MNRAS/414/1397;Radio study of double-double radio galaxy 3C293 (Joshi+, 2011)',
 'J/MNRAS/426/3334;Australia Telescope Large Area Survey (Mao+, 2012)',
 'J/MNRAS/435/650;325MHz GMRT survey of Herschel-ATLAS/GAMA fields (Mauch+, 2013)',
 'J/MNRAS/465/997;Low-luminosity radio-loud AGN (Chandola+, 2017)']

In [257]:
Vizier.get_catalogs('J/MNRAS/465/997')

TableList with 2 tables:
	'0:J/MNRAS/465/997/sample' with 20 column(s) and 100 row(s)
	'1:J/MNRAS/465/997/tablea3' with 15 column(s) and 100 row(s)

In [258]:
catalogo_Saikia_1 = Vizier.get_catalogs('J/MNRAS/465/997')[0]

In [259]:
catalogo_Saikia_1

<Table length=100>
Samp  Seq   RAJ2000    DEJ2000  ...    FS_II_      e_FS_II_   OClass RClass
            'h:m:s'    'd:m:s'  ... 1e-20W.m**-2 1e-20W.m**-2
str1 int16   str10       str9   ...   float64      float64     str4   str1
---- ----- ---------- --------- ... ------------ ------------ ------ ------
   D     1 07 57 56.7 +39 59 36 ...      257.189       10.055   HERG      C
   D     2 08 06 01.5 +19 06 15 ...      136.350        9.655   HERG      E
   D     3 08 09 38.9 +34 55 37 ...       34.271       10.370   LERG      E
   D     4 08 36 37.8 +44 01 10 ...      254.389       13.003   HERG      C
   D     5 08 43 07.1 +45 37 43 ...        2.635        5.381   LERG      C
   D     6 09 09 37.4 +19 28 08 ...      593.890       26.776   LERG      C
   D     7 09 35 51.6 +61 21 11 ...      415.602       12.743      U      M
   D     8 10 20 53.7 +48 31 24 ...      120.190        9.524   LERG      E
   D     9 10 53 27.2 +20 58 36 ...       65.221        9.054   LERG      C
 ...   ...        ...       ... ...          ...          ...    ...    ...
   N    91 15 53 43.6 +23 48 25 ...       81.864        8.672   HERG      E
   N    92 15 56 03.9 +24 26 53 ...       57.715       24.638   LERG      E
   N    93 15 56 11.6 +28 11 33 ...        3.538       12.021   LERG      E
   N    94 15 59 54.0 +44 42 32 ...      155.612       17.338   LERG      C
   N    95 16 04 26.5 +17 44 31 ...      408.208       20.351   LERG      C
   N    96 16 06 16.0 +18 15 00 ...      126.840       25.462   LERG      E
   N    97 16 08 21.1 +28 28 43 ...      140.174       13.342   LERG      E
   N    98 16 14 19.6 +50 27 56 ...      319.541       18.491   LERG      E
   N    99 16 15 41.2 +47 11 12 ...       16.506        6.894   LERG      E
   N   100 16 24 24.5 +48 31 42 ...      238.491       15.361   LERG      C

In [260]:
catalogo_Saikia_2 = Vizier.get_catalogs('J/MNRAS/465/997')[1]

In [261]:
catalogo_Saikia_2

<Table length=100>
 Seq          WISE         W1mag  ...    LogSM          LogSFR       LogsSFR
                            mag   ... log(solMass) log(solMass/yr) log(yr**-1)
int16        str19        float32 ...   float32        float32       float32
----- ------------------- ------- ... ------------ --------------- -----------
    1 J075607.17+383400.4  14.101 ...       11.602          -0.342     -12.003
    2 J075756.71+395936.1  12.832 ...       10.831          -0.121     -11.008
    3 J075828.11+374711.8  10.837 ...       11.620          -0.554     -12.226
    4 J075847.02+270515.7  12.877 ...       10.739           0.381     -10.383
    5 J080041.93+321728.8  13.789 ...       11.729          -0.091     -11.897
    6 J080601.54+190614.6  12.462 ...       11.399           0.662     -10.785
    7 J080938.85+345537.3  12.477 ...       11.198           0.783     -10.473
    8 J081827.34+281402.8  13.804 ...       11.085           1.427      -9.697
    9 J081854.10+224744.9  12.788 ...       11.286          -0.876     -12.214
  ...                 ...     ... ...          ...             ...         ...
   91 J160246.39+524358.5  12.512 ...       11.432           1.273     -10.209
   92 J160332.09+171155.3  10.934 ...       11.269          -0.992     -12.313
   93 J160338.05+155402.4  13.116 ...       11.603           0.785     -10.875
   94 J160426.51+174431.2  11.381 ...       10.847          -1.008     -11.921
   95 J160616.02+181459.8  11.002 ...       11.293          -0.579     -11.906
   96 J160821.14+282843.3  11.863 ...       11.197          -0.771     -12.022
   97 J161217.62+282546.3  11.759 ...       11.360          -0.566     -11.993
   98 J161419.64+502756.2  11.961 ...       11.393          -0.860     -12.310
   99 J161541.21+471111.8  13.050 ...       11.272           1.070     -10.267
  100 J162424.49+483142.4  11.877 ...       11.381          -1.013     -12.432

In [262]:
catalogo_Saikia_1.write('../CatalogosRadio/catalogo_Saikia_1.ecsv', format='ascii.ecsv', overwrite=True)

In [263]:
catalogo_Saikia_2.write('../CatalogosRadio/catalogo_Saikia_2.ecsv', format='ascii.ecsv', overwrite=True)

In [264]:
dfSaikia2= catalogo_Saikia_2.to_pandas()
dfSaikia1= catalogo_Saikia_1.to_pandas()

In [265]:
catalogo_S = Simbad.query_bibobj('2018A&A...616A.152S')

In [266]:
catalogo_S

dfS= catalogo_S.to_pandas()
dfS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MAIN_ID           154 non-null    object
 1   RA                154 non-null    object
 2   DEC               154 non-null    object
 3   RA_PREC           154 non-null    int16
 4   DEC_PREC          154 non-null    int16
 5   COO_ERR_MAJA      113 non-null    float32
 6   COO_ERR_MINA      113 non-null    float32
 7   COO_ERR_ANGLE     154 non-null    int16
 8   COO_QUAL          154 non-null    object
 9   COO_WAVELENGTH    154 non-null    object
 10  COO_BIBCODE       154 non-null    object
 11  SCRIPT_NUMBER_ID  154 non-null    int32
dtypes: float32(2), int16(3), int32(1), object(6)
memory usage: 10.1+ KB

# Laura

In [267]:
laura = Table.read('../CatalogosRadio/Laura.csv') #Leer tabla

dfLaura = laura.to_pandas()
dfLaura

      Objeto            RA           DEC Redshift Magnitud (V)
0   NGC 0266   00 49 47.80   +32 16 39.8   0,0155        11,82
1   NGC 0315   00 57 48.88   +30 21 08.8   0,0165         11,6
2   NGC 0410  01 10 58.904  +33 09 06.81   0,0177        11,48
3   NGC 0474   01 20 06.70   +03 24 55.0   0,0077        11,52
4   NGC 0524   01 24 47.72     +09 32 20    0,008        10,35
..       ...           ...           ...      ...          ...
70  NGC 6482   17 51 48.81   +23 04 19.0   0,0131        11,33
71  NGC 7285   22 28 38.00   −24 50 26.8   0,0144           --
72  NGC 7331   22 37 04.09   +34 24 56.3   0,0038         9,41
73   IC 1459   22 57 10.60   −36 27 44.0   0,0055        10,54
74  NGC 7743   23 44 21.14   +09 56 02.7   0,0057        12,43

[75 rows x 5 columns]

In [268]:
dfLaura['Objeto']

0     NGC 0266
1     NGC 0315
2     NGC 0410
3     NGC 0474
4     NGC 0524
        ...
70    NGC 6482
71    NGC 7285
72    NGC 7331
73     IC 1459
74    NGC 7743
Name: Objeto, Length: 75, dtype: object

# SIMBAD, BALDI

In [269]:
limitedSimbad = Simbad()

limitedSimbad.ROW_LIMIT = 6

In [270]:
catalogo_Baldi = Simbad.query_bibobj('2018MNRAS.476.3478B')

In [271]:
catalogo_Baldi

<Table length=125>
 MAIN_ID        RA           DEC      ...     COO_BIBCODE     SCRIPT_NUMBER_ID
             "h:m:s"       "d:m:s"    ...
  object      str13         str13     ...        object            int32
--------- ------------- ------------- ... ------------------- ----------------
NGC  7817  00 03 58.899  +20 45 08.42 ... 2006AJ....131.1163S                1
  IC   10   00 20 23.16   +59 17 34.7 ... 1999ApJS..125..409C                1
NGC   147  00 33 12.120  +48 30 31.46 ... 2006AJ....131.1163S                1
NGC   185 00 38 57.9400 +48 20 15.035 ... 2020yCat.1350....0G                1
NGC   189      00 39 32      +61 05.4 ... 2020A&A...633A..99C                1
    M 110 00 40 22.0572 +41 41 07.507 ... 2020yCat.1350....0G                1
    M  32  00 42 41.825  +40 51 54.61 ... 2006AJ....131.1163S                1
    M  31  00 42 44.330  +41 16 07.50 ... 2006AJ....131.1163S                1
NGC   266 00 49 47.8149 +32 16 39.786 ... 2020yCat.1350....0G                1
      ...           ...           ... ...                 ...              ...
NGC  6946  20 34 52.332  +60 09 13.24 ... 2006AJ....131.1163S                1
NGC  6951 20 37 14.1228 +66 06 20.049 ... 2020yCat.1350....0G                1
NGC  7080 21 30 01.9198 +26 43 04.373 ... 2020yCat.1350....0G                1
NGC  7217 22 07 52.3984 +31 21 33.632 ... 2020yCat.1350....0G                1
NGC  7331 22 37 04.0506 +34 24 56.800 ... 2020yCat.1350....0G                1
NGC  7332 22 37 24.5373 +23 47 53.830 ... 2020yCat.1350....0G                1
NGC  7457 23 00 59.9263 +30 08 41.764 ... 2020yCat.1350....0G                1
NGC  7640 23 22 06.5746 +40 50 43.114 ... 2020yCat.1350....0G                1
NGC  7741  23 43 54.375  +26 04 32.07 ... 2006AJ....131.1163S                1
NGC  7798 23 59 25.5026 +20 44 59.355 ... 2018yCat.1345....0G                1

In [272]:
catalogo_Baldi.write('../CatalogosRadio/catalogo_Baldi.ecsv', format='ascii.ecsv', overwrite=True)

In [273]:
dfBaldi = catalogo_Baldi.to_pandas()
dfBaldi

,MAIN_ID,RA,DEC,RA_PREC,DEC_PREC,COO_ERR_MAJA,COO_ERR_MINA,COO_ERR_ANGLE,COO_QUAL,COO_WAVELENGTH,COO_BIBCODE,SCRIPT_NUMBER_ID
0,NGC 7817,00 03 58.899,+20 45 08.42,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
1,IC 10,00 20 23.16,+59 17 34.7,6,6,10800.000000,10800.0000,90,D,,1999ApJS..125..409C,1
2,NGC 147,00 33 12.120,+48 30 31.46,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
3,NGC 185,00 38 57.9400,+48 20 15.035,14,14,25.095501,7.0605,90,C,O,2020yCat.1350....0G,1
4,NGC 189,00 39 32,+61 05.4,4,4,NaN,NaN,0,D,O,2020A&A...633A..99C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
120,NGC 7332,22 37 24.5373,+23 47 53.830,14,14,0.292300,0.3253,90,A,O,2020yCat.1350....0G,1
121,NGC 7457,23 00 59.9263,+30 08 41.764,14,14,0.104700,0.1328,90,A,O,2020yCat.1350....0G,1
122,NGC 7640,23 22 06.5746,+40 50 43.114,14,14,3.167100,7.1131,90,C,O,2020yCat.1350....0G,1
123,NGC 7741,23 43 54.375,+26 04 32.07,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
124,NGC 7798,23 59 25.5026,+20 44 59.355,14,14,3.944400,2.4878,90,C,O,2018yCat.1345....0G,1

# Nagar

In [274]:
catalog_list = Vizier.find_catalogs('Nagar')
['{};{}'.format(k,v.description) for k,v in catalog_list.items()]

['J/ApJ/807/150;230GHz VLBI observations of M87 (Akiyama+, 2015)',
 'J/ApJ/859/60;Sgr A* 1.3mm VLBI observations with the EHT in 2013 (Lu+, 2018)',
 'J/ApJ/879/10;2015-2017 LIGO obs. analysis for 221 pulsars (Abbott+, 2019)',
 'J/A+A/409/115;VLA imaging of IRAS 1 Jy ULIRG sample (Nagar+, 2003)',
 'J/A+A/435/521;Radio Sources in Low-Luminosity AGNs. IV (Nagar+, 2005)',
 'J/A+A/597/A41;ALMA Frontier Fields Survey. I. (Gonzalez-Lopez+, 2017)',
 'J/A+A/621/A83;NGC 1566 ALMA and Gemini-GMOS/IFU datacubes (Slater+, 2019)',
 'J/A+A/633/A127;Jet-driven outflow in ESO 420-G13 (Fernandez-Ontiveros+, 2020)',
 'J/A+A/640/A69;3C 279 Event Horizon Telescope imaging (Kim+, 2020)',
 'J/AJ/120/1364;Abundances in M3 and M13 (Cavallo+, 2000)']

In [275]:
Vizier.get_catalogs('J/A+A/435/521')

TableList with 3 tables:
	'0:J/A+A/435/521/table1' with 15 column(s) and 197 row(s)
	'1:J/A+A/435/521/table2' with 15 column(s) and 44 row(s)
	'2:J/A+A/435/521/notes' with 2 column(s) and 35 row(s)

In [276]:
catalogo_Nagar = Vizier.get_catalogs('J/A+A/435/521')[0]

In [277]:
catalogo_Nagar

<Table length=197>
  Name  AType  TType    Dist   Delta  ...  Note Simbad NED    _RA      _DE
                        Mpc    arcsec ...                     deg      deg
  str7   str9 float32 float32 float32 ... int16  str6  str3 float64  float64
------- ----- ------- ------- ------- ... ----- ------ ---- -------- --------
  IC239  L2::     6.0    16.8      -- ...    -- Simbad  NED  39.1163  38.9690
  IC356    T2     2.0    18.1      -- ...     4 Simbad  NED  61.9436  69.8126
  IC520   T2:     2.0    47.0      -- ...     4 Simbad  NED 133.4258  73.4908
 IC1727 T2/L2     9.0     8.2      -- ...    -- Simbad  NED  26.8748  27.3330
 NGC185    S2    -5.0     0.7      -- ...    -- Simbad  NED   9.7392  48.3373
 NGC266  L1.9     2.0    62.4     2.0 ...    -- Simbad  NED  12.4499  32.2776
 NGC315  L1.9    -4.0    65.8      -- ...     9 Simbad  NED  14.4537  30.3524
 NGC404    L2    -3.0     2.4      -- ...    -- Simbad  NED  17.3626  35.7180
 NGC410   T2:    -4.0    70.6      -- ...     4 Simbad  NED  17.7460  33.1520
    ...   ...     ...     ...     ... ...   ...    ...  ...      ...      ...
NGC6703  L2::    -2.5    35.9      -- ...    -- Simbad  NED 281.8286  45.5503
NGC6951    S2     4.0    24.1      -- ...    -- Simbad  NED 309.3100  66.1055
NGC7177    T2     3.0    18.2      -- ...    -- Simbad  NED 330.1719  17.7379
NGC7217    L2     2.0    16.0     2.9 ...     2 Simbad  NED 331.9692  31.3591
NGC7331    T2     3.0    14.3      -- ...    -- Simbad  NED 339.2679  34.4162
NGC7479  S1.9     5.0    32.4     1.0 ...    -- Simbad  NED 346.2362  12.3231
NGC7626  L2::    -5.0    45.6     2.9 ...    -- Simbad  NED 350.1778   8.2164
NGC7742 T2/L2     3.0    22.2      -- ...    -- Simbad  NED 356.0661  10.7669
NGC7743    S2    -1.0    24.4     1.1 ...    -- Simbad  NED 356.0893   9.9343
NGC7814  L2::     2.0    15.1      -- ...    -- Simbad  NED   0.8121  16.1454

In [278]:
catalogo_Nagar.write('../CatalogosRadio/catalogo_Nagar.ecsv', format='ascii.ecsv', overwrite=True)

In [279]:
dfN = catalogo_Nagar.to_pandas()
dfN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       197 non-null    object
 1   AType      197 non-null    object
 2   TType      197 non-null    float32
 3   Dist       197 non-null    float32
 4   Delta      60 non-null     float32
 5   Sp15GHz    68 non-null     float32
 6   l_St15GHz  197 non-null    object
 7   St15GHz    190 non-null    float32
 8   l_Lp15GHz  197 non-null    object
 9   Lp15GHz    193 non-null    float32
 10  Note       43 non-null     Int16
 11  Simbad     197 non-null    object
 12  NED        197 non-null    object
 13  _RA        197 non-null    float64
 14  _DE        197 non-null    float64
dtypes: Int16(1), float32(6), float64(2), object(6)
memory usage: 17.6+ KB

# Crossmacth, por nombre

&nbsp;
Se define una función que tiene como entrada dos tablas y la columna respectiva a cada una para hacer el crossmatch. 

&nbsp;
 --> Para cada elemento hacemos in .replace(" ",""), así eliminamos posibles diferencias de lectura (solo nos centramos en los caracteres tales que sean numeros o letras).

&nbsp;
El otro parametro que entramos es: matched. Será una lista que habrá que definir como vacía cada vez que se llame a la función.

&nbsp;
Ejemplo para Baldi con Saikia.

In [328]:
p =0

def crosstable (table_1, col1, table_2,col2,matched):
    p = 0
    for i in table_1[col1]:
        i = i.replace(" ","")
        for a in table_2[col2]:
            a = a.replace(" ","")
            if (i == a):
                matched.append(i)
                p = p+1
    print (p)
    print (pd.DataFrame(matched,columns=['Object']))
    
    return

matchedA=[]        
A = crosstable(dfBaldi, 'MAIN_ID', dfS, 'MAIN_ID',matchedA)     


#dfmatch = pd.DataFrame(matched,columns=['Object'])
#(dfmatch)

40
       Object
0      NGC185
1         M31
2      NGC266
3      NGC315
4      NGC410
5      NGC777
6      NGC841
7     NGC2273
8     NGC2541
9     NGC2681
10      IC520
11    NGC2655
12    NGC2841
13    NGC3414
14    NGC3675
15    NGC4013
16    NGC4051
17    NGC4151
18        M87
19    NGC5033
20        M51
21    NGC5195
22      3C286
23    NGC5273
24    NGC5297
25    NGC5322
26    NGC5353
27    NGC5354
28    NGC5390
29    NGC5377
30    NGC5395
31    NGC5448
32    NGC5656
33       M102
34    NGC5879
35    NGC5982
36    NGC5985
37  NAMESgrA*
38    NGC6703
39    NGC6951

&nbsp;
Procedimiento original para la creación de una tabla aislada. Más adelante la función donde se explicará.

In [281]:
RAtab = []
DECtab = []
names = []
coord = []
p = 0
count=0
for a in dfBaldi['MAIN_ID']:
    a = a.replace(" ","") 
    for i in matchedA:
        i = i.replace(" ","")
        if i == a:
            RA=dfBaldi['RA'][p]
            RAtab.append(RA)
            DEC= dfBaldi['DEC'][p]
            DECtab.append(DEC)
            ID= dfBaldi['MAIN_ID'][p]
            names.append(ID)
    p = p+1
    

coord = []
for n,r,d in zip(names,RAtab, DECtab):
    coordenadas = [n,r,d]
    coord.append(coordenadas)

df2= pd.DataFrame(coord, columns=['Object', 'RA','DEC']) 
print(df2)

         Object             RA            DEC
0     NGC   185  00 38 57.9400  +48 20 15.035
1         M  31   00 42 44.330   +41 16 07.50
2     NGC   266  00 49 47.8149  +32 16 39.786
3     NGC   315  00 57 48.8590  +30 21 08.842
4     NGC   410  01 10 58.9016  +33 09 07.053
5     NGC   777  02 00 14.9065  +31 25 45.850
6     NGC   841  02 11 17.3713  +37 29 49.713
7     NGC  2273  06 50 08.6691  +60 50 44.864
8     NGC  2541  08 14 40.1160  +49 03 42.021
9     NGC  2681  08 53 32.7183  +51 18 49.159
10      IC  520  08 53 42.2471  +73 29 27.418
11    NGC  2655   08 55 37.731   +78 13 23.10
12    NGC  2841  09 22 02.6778  +50 58 35.737
13    NGC  3414  10 51 16.2099  +27 58 30.297
14    NGC  3675  11 26 08.5641  +43 35 09.587
15    NGC  4013   11 58 31.417   +43 56 49.28
16    NGC  4051  12 03 09.6101  +44 31 52.682
17    NGC  4151  12 10 32.5759  +39 24 21.063
18        M  87  12 30 49.4233  +12 23 28.043
19    NGC  5033   13 13 27.535   +36 35 37.14
20        M  51   13 29 52.698   +47 11 42.93
21    NGC  5195   13 29 59.590   +47 15 58.06
22       3C 286  13 31 08.2883  +30 30 32.960
23    NGC  5273  13 42 08.3801  +35 39 15.467
24    NGC  5297   13 46 23.694   +43 52 19.34
25    NGC  5322    13 49 15.24    +60 11 25.8
26    NGC  5353  13 53 26.7104  +40 16 59.200
27    NGC  5354  13 53 26.7262  +40 18 09.928
28    NGC  5390  13 55 39.9385  +40 27 42.380
29    NGC  5377  13 56 16.6722  +47 14 08.568
30    NGC  5395  13 58 37.9605  +37 25 28.161
31    NGC  5448   14 02 50.072   +49 10 21.53
32    NGC  5656  14 30 25.5100  +35 19 15.733
33        M 102   15 06 29.561   +55 45 47.91
34    NGC  5879  15 09 46.7271  +57 00 00.538
35    NGC  5982   15 38 39.778   +59 21 21.21
36    NGC  5985  15 39 37.0545  +59 19 55.216
37  NAME Sgr A*  17 45 40.0359  -29 00 28.169
38    NGC  6703  18 47 18.8166  +45 33 02.274
39    NGC  6951  20 37 14.1228  +66 06 20.049

Ejemplo para llamar a la función "crosstable".
&nbsp;
Crossmatch por nombre entre el catalogo de Saikia y el de Laura. La lista de objetos coincidente de guarda en matchedB[], definida como vacía, anteriormente.

In [282]:
matchedB=[]
B = crosstable (catalogo_S, 'MAIN_ID', dfLaura, 'Objeto', matchedB)
print (B)
print(matchedB)

32
     Object
0   NGC2681
1   NGC2655
2   NGC2787
3   NGC2841
4   NGC3226
5   NGC3414
6   NGC3628
7   NGC3642
8   NGC3718
9   NGC3898
10  NGC3945
11  NGC3998
12  NGC4036
13  NGC4111
14  NGC4125
15  NGC4143
16  NGC4203
17  NGC4261
18  NGC4278
19  NGC4314
20  NGC4450
21  NGC4589
22  NGC4636
23  NGC4750
24  NGC4772
25  NGC5363
26  NGC5746
27  NGC5813
28  NGC5838
29  NGC5846
30  NGC6482
31  NGC7743
None
['NGC2681', 'NGC2655', 'NGC2787', 'NGC2841', 'NGC3226', 'NGC3414', 'NGC3628', 'NGC3642', 'NGC3718', 'NGC3898', 'NGC3945', 'NGC3998', 'NGC4036', 'NGC4111', 'NGC4125', 'NGC4143', 'NGC4203', 'NGC4261', 'NGC4278', 'NGC4314', 'NGC4450', 'NGC4589', 'NGC4636', 'NGC4750', 'NGC4772', 'NGC5363', 'NGC5746', 'NGC5813', 'NGC5838', 'NGC5846', 'NGC6482', 'NGC7743']

Baldi-Laura

In [304]:
matchedC=[]
C = crosstable(catalogo_Baldi, 'MAIN_ID', dfLaura, 'Objeto', matchedC)
print (C)
print(matchedC)

8
    Object
0  NGC2639
1  NGC2681
2  NGC2685
3  NGC2655
4  NGC2841
5  NGC3414
6  NGC5005
7  NGC7331
None
['NGC2639', 'NGC2681', 'NGC2685', 'NGC2655', 'NGC2841', 'NGC3414', 'NGC5005', 'NGC7331']

Nagar-Laura

In [307]:
matchedD=[]
D = crosstable(catalogo_Nagar, 'Name', dfLaura, 'Objeto', matchedD)
print (D)
print(matchedD)

56
     Object
0   NGC2655
1   NGC2681
2   NGC2685
3   NGC2787
4   NGC2841
5   NGC3226
6   NGC3245
7   NGC3379
8   NGC3414
9   NGC3507
10  NGC3607
11  NGC3608
12  NGC3623
13  NGC3627
14  NGC3628
15  NGC3642
16  NGC3718
17  NGC3898
18  NGC3945
19  NGC3998
20  NGC4036
21  NGC4111
22  NGC4125
23  NGC4143
24  NGC4203
25  NGC4261
26  NGC4278
27  NGC4314
28  NGC4321
29  NGC4374
30  NGC4438
31  NGC4450
32  NGC4457
33  NGC4459
34  NGC4486
35  NGC4494
36  NGC4552
37  NGC4579
38  NGC4589
39  NGC4596
40  NGC4636
41  NGC4698
42  NGC4736
43  NGC4750
44  NGC4772
45  NGC5005
46  NGC5055
47  NGC5363
48  NGC5746
49  NGC5813
50  NGC5838
51  NGC5846
52  NGC5866
53  NGC6482
54  NGC7331
55  NGC7743
None
['NGC2655', 'NGC2681', 'NGC2685', 'NGC2787', 'NGC2841', 'NGC3226', 'NGC3245', 'NGC3379', 'NGC3414', 'NGC3507', 'NGC3607', 'NGC3608', 'NGC3623', 'NGC3627', 'NGC3628', 'NGC3642', 'NGC3718', 'NGC3898', 'NGC3945', 'NGC3998', 'NGC4036', 'NGC4111', 'NGC4125', 'NGC4143', 'NGC4203', 'NGC4261', 'NGC4278', 'NGC4314', 'NGC4321', 'NGC4374', 'NGC4438', 'NGC4450', 'NGC4457', 'NGC4459', 'NGC4486', 'NGC4494', 'NGC4552', 'NGC4579', 'NGC4589', 'NGC4596', 'NGC4636', 'NGC4698', 'NGC4736', 'NGC4750', 'NGC4772', 'NGC5005', 'NGC5055', 'NGC5363', 'NGC5746', 'NGC5813', 'NGC5838', 'NGC5846', 'NGC5866', 'NGC6482', 'NGC7331', 'NGC7743']

Nagar-Saikia

In [329]:
matchedE=[]
E = crosstable(catalogo_Nagar, 'Name', dfLaura, 'Objeto', matchedE)
print (E)
print(matchedE)

56
     Object
0   NGC2655
1   NGC2681
2   NGC2685
3   NGC2787
4   NGC2841
5   NGC3226
6   NGC3245
7   NGC3379
8   NGC3414
9   NGC3507
10  NGC3607
11  NGC3608
12  NGC3623
13  NGC3627
14  NGC3628
15  NGC3642
16  NGC3718
17  NGC3898
18  NGC3945
19  NGC3998
20  NGC4036
21  NGC4111
22  NGC4125
23  NGC4143
24  NGC4203
25  NGC4261
26  NGC4278
27  NGC4314
28  NGC4321
29  NGC4374
30  NGC4438
31  NGC4450
32  NGC4457
33  NGC4459
34  NGC4486
35  NGC4494
36  NGC4552
37  NGC4579
38  NGC4589
39  NGC4596
40  NGC4636
41  NGC4698
42  NGC4736
43  NGC4750
44  NGC4772
45  NGC5005
46  NGC5055
47  NGC5363
48  NGC5746
49  NGC5813
50  NGC5838
51  NGC5846
52  NGC5866
53  NGC6482
54  NGC7331
55  NGC7743
None
['NGC2655', 'NGC2681', 'NGC2685', 'NGC2787', 'NGC2841', 'NGC3226', 'NGC3245', 'NGC3379', 'NGC3414', 'NGC3507', 'NGC3607', 'NGC3608', 'NGC3623', 'NGC3627', 'NGC3628', 'NGC3642', 'NGC3718', 'NGC3898', 'NGC3945', 'NGC3998', 'NGC4036', 'NGC4111', 'NGC4125', 'NGC4143', 'NGC4203', 'NGC4261', 'NGC4278', 'NGC4314', 'NGC4321', 'NGC4374', 'NGC4438', 'NGC4450', 'NGC4457', 'NGC4459', 'NGC4486', 'NGC4494', 'NGC4552', 'NGC4579', 'NGC4589', 'NGC4596', 'NGC4636', 'NGC4698', 'NGC4736', 'NGC4750', 'NGC4772', 'NGC5005', 'NGC5055', 'NGC5363', 'NGC5746', 'NGC5813', 'NGC5838', 'NGC5846', 'NGC5866', 'NGC6482', 'NGC7331', 'NGC7743']

# Función crear tabla

&nbsp;
Se define una función para crear una tabla a que contenga los elementos coincidentes en dos catálogos y las columnas que nos interesen. 
&nbsp;

 --> **Entrada:**  
 
 Lista de coincidentes (proviene de la funcion crosstable),  
 
 tabla de referencia + los argumentos que nos interesen de la misma (por ahora 3, "name, "RA", Y "DEC"),  
 
 tabla secundaria + los argumentos que correspondasn (N,R,D).   
 
 Se hace general por si nos interesa combinar información de las tablas.

&nbsp;
 --> Debería devolver una tabla que pueda descargar en csv. De momento solo printea, en un futuro, cuando se tenga claro qué guardar, se descargará.

In [294]:

def crear_tabla(crossmatched, tableref, name, RA, DEC, tablasec, N,R,D):
    RAtab = []
    DECtab = []
    names = []
    coord = []
    p = 0
    for a in tableref[name]:
        a = a.replace(" ","")
        for i in crossmatched:
            i = i.replace(" ","")
            if i == a:
                RAi=tableref[RA][p]
                RAtab.append(RAi)
                DECi= tableref[DEC][p]
                DECtab.append(DECi)
                ID= tableref[name][p]
                names.append(ID)
                
        p = p+1
        
    coord = []
    for n,r,d in zip(names,RAtab, DECtab):
        coordenadas = [n, r,d]
        coord.append(coordenadas)
            
           
    tabla=(pd.DataFrame(coord, columns=['Object', 'RA', 'DEC']))
    #print(p)
    #print(tabla)

    return tabla

Ejemplo: CT_B_S = CrossTable_Baldi_Saikia

In [295]:
CT_B_S= crear_tabla(matchedA, dfBaldi, 'MAIN_ID', 'RA','DEC', dfS, 'MAIN_ID', 'RA', 'DEC')
CT_B_S

         Object             RA            DEC
0     NGC   185  00 38 57.9400  +48 20 15.035
1         M  31   00 42 44.330   +41 16 07.50
2     NGC   266  00 49 47.8149  +32 16 39.786
3     NGC   315  00 57 48.8590  +30 21 08.842
4     NGC   410  01 10 58.9016  +33 09 07.053
5     NGC   777  02 00 14.9065  +31 25 45.850
6     NGC   841  02 11 17.3713  +37 29 49.713
7     NGC  2273  06 50 08.6691  +60 50 44.864
8     NGC  2541  08 14 40.1160  +49 03 42.021
9     NGC  2681  08 53 32.7183  +51 18 49.159
10      IC  520  08 53 42.2471  +73 29 27.418
11    NGC  2655   08 55 37.731   +78 13 23.10
12    NGC  2841  09 22 02.6778  +50 58 35.737
13    NGC  3414  10 51 16.2099  +27 58 30.297
14    NGC  3675  11 26 08.5641  +43 35 09.587
15    NGC  4013   11 58 31.417   +43 56 49.28
16    NGC  4051  12 03 09.6101  +44 31 52.682
17    NGC  4151  12 10 32.5759  +39 24 21.063
18        M  87  12 30 49.4233  +12 23 28.043
19    NGC  5033   13 13 27.535   +36 35 37.14
20        M  51   13 29 52.698   +47 11 42.93
21    NGC  5195   13 29 59.590   +47 15 58.06
22       3C 286  13 31 08.2883  +30 30 32.960
23    NGC  5273  13 42 08.3801  +35 39 15.467
24    NGC  5297   13 46 23.694   +43 52 19.34
25    NGC  5322    13 49 15.24    +60 11 25.8
26    NGC  5353  13 53 26.7104  +40 16 59.200
27    NGC  5354  13 53 26.7262  +40 18 09.928
28    NGC  5390  13 55 39.9385  +40 27 42.380
29    NGC  5377  13 56 16.6722  +47 14 08.568
30    NGC  5395  13 58 37.9605  +37 25 28.161
31    NGC  5448   14 02 50.072   +49 10 21.53
32    NGC  5656  14 30 25.5100  +35 19 15.733
33        M 102   15 06 29.561   +55 45 47.91
34    NGC  5879  15 09 46.7271  +57 00 00.538
35    NGC  5982   15 38 39.778   +59 21 21.21
36    NGC  5985  15 39 37.0545  +59 19 55.216
37  NAME Sgr A*  17 45 40.0359  -29 00 28.169
38    NGC  6703  18 47 18.8166  +45 33 02.274
39    NGC  6951  20 37 14.1228  +66 06 20.049

Ejemplo: CT_S_L = CrossTable_Saikia_Laura

In [298]:
CT_S_L = crear_tabla(matchedB, dfS, 'MAIN_ID', 'RA','DEC', dfLaura, 'Objeto', 'Coordenadas', 'Redshift')
CT_S_L

       Object             RA            DEC
0   NGC  2681  08 53 32.7183  +51 18 49.159
1   NGC  2655   08 55 37.731   +78 13 23.10
2   NGC  2787  09 19 18.6046  +69 12 11.630
3   NGC  2841  09 22 02.6778  +50 58 35.737
4   NGC  3226  10 23 27.0064  +19 53 54.674
5   NGC  3414  10 51 16.2099  +27 58 30.297
6   NGC  3628   11 20 17.018   +13 35 22.16
7   NGC  3642  11 22 17.9010  +59 04 28.275
8   NGC  3718  11 32 34.8571  +53 04 04.520
9   NGC  3898   11 49 15.370   +56 05 03.66
10  NGC  3945  11 53 13.6081  +60 40 32.125
11  NGC  3998  11 57 56.1334  +55 27 12.922
12  NGC  4036  12 01 26.7603  +61 53 44.625
13  NGC  4111  12 07 03.1334  +43 03 56.345
14  NGC  4125   12 08 06.017   +65 10 26.88
15  NGC  4143  12 09 36.0679  +42 32 03.031
16  NGC  4203  12 15 05.0549  +33 11 50.383
17  NGC  4261  12 19 23.2160  +05 49 29.700
18  NGC  4278  12 20 06.8253  +29 16 50.713
19  NGC  4314  12 22 32.0223  +29 53 43.814
20  NGC  4450  12 28 29.5910  +17 05 05.976
21  NGC  4589  12 37 24.9947  +74 11 30.861
22  NGC  4636  12 42 49.8333  +02 41 15.951
23  NGC  4750  12 50 07.3113  +72 52 28.653
24  NGC  4772  12 53 29.1636  +02 10 06.146
25  NGC  5363   13 56 07.244   +05 15 16.92
26  NGC  5746   14 44 56.005   +01 57 17.06
27  NGC  5813  15 01 11.2302  +01 42 07.141
28  NGC  5838  15 05 26.2447  +02 05 57.349
29  NGC  5846   15 06 29.253   +01 36 20.29
30  NGC  6482  17 51 48.8339  +23 04 18.889
31  NGC  7743  23 44 21.1607  +09 56 02.970

Compruebo ahora que el crossmatch hecho ha funcionado. Para ello cruzo la lista matchedB, con el catálogo de Laura. Todos tienen que estar contenidos.  
**¡Correcto!**

In [301]:
#Compruebo
matchedp=[]
B = crosstable(matchedB, 0, dfLaura, 'Objeto', matchedB)

0
     Object
0   NGC2681
1   NGC2655
2   NGC2787
3   NGC2841
4   NGC3226
5   NGC3414
6   NGC3628
7   NGC3642
8   NGC3718
9   NGC3898
10  NGC3945
11  NGC3998
12  NGC4036
13  NGC4111
14  NGC4125
15  NGC4143
16  NGC4203
17  NGC4261
18  NGC4278
19  NGC4314
20  NGC4450
21  NGC4589
22  NGC4636
23  NGC4750
24  NGC4772
25  NGC5363
26  NGC5746
27  NGC5813
28  NGC5838
29  NGC5846
30  NGC6482
31  NGC7743

Ejemplo: CT_B_L = CrossTable_Baldi_Laura

In [305]:
CT_B_L = crear_tabla(matchedC, dfBaldi, 'MAIN_ID', 'RA','DEC', dfLaura, 'Objeto', 'Coordenadas', 'Redshift')
CT_B_L

      Object             RA            DEC
0  NGC  2639  08 43 38.0682  +50 12 19.942
1  NGC  2681  08 53 32.7183  +51 18 49.159
2  NGC  2685  08 55 34.7027  +58 44 03.876
3  NGC  2655   08 55 37.731   +78 13 23.10
4  NGC  2841  09 22 02.6778  +50 58 35.737
5  NGC  3414  10 51 16.2099  +27 58 30.297
6  NGC  5005   13 10 56.312   +37 03 32.19
7  NGC  7331  22 37 04.0506  +34 24 56.800

Ejemplo: CT_N_L = CrossTable_Nagar_Laura

In [310]:
CT_N_L = crear_tabla(matchedD, dfN, 'Name', '_RA','_DE', dfLaura, 'Objeto', 'Coordenadas', 'Redshift')
CT_N_L

     Object        RA      DEC
0   NGC2655  133.9118  78.2237
1   NGC2681  133.3860  51.3132
2   NGC2685  133.8950  58.7338
3   NGC2787  139.8287  69.2033
4   NGC2841  140.5085  50.9777
5   NGC3226  155.8628  19.8985
6   NGC3245  156.8272  28.5069
7   NGC3379  161.9573  12.5818
8   NGC3414  162.8175  27.9750
9   NGC3507  165.8561  18.1355
10  NGC3607  169.2281  18.0517
11  NGC3608  169.2461  18.1485
12  NGC3623  169.7324  13.0923
13  NGC3627  170.0628  12.9893
14  NGC3628  170.0705  13.5871
15  NGC3642  170.5743  59.0741
16  NGC3718  173.1443  53.0678
17  NGC3898  177.3145  56.0841
18  NGC3945  178.3075  60.6754
19  NGC3998  179.4848  55.4531
20  NGC4036  180.3616  61.8958
21  NGC4111  181.7628  43.0656
22  NGC4125  182.0262  65.1742
23  NGC4143  182.4008  42.5340
24  NGC4203  183.7707  33.1972
25  NGC4261  184.8469   5.8257
26  NGC4278  185.0284  29.2808
27  NGC4314  185.6335  29.8955
28  NGC4321  185.7290  15.8221
29  NGC4374  186.2656  12.8870
30  NGC4438  186.9413  13.0090
31  NGC4450  187.1235  17.0847
32  NGC4457  187.2458   3.5712
33  NGC4459  187.2505  13.9785
34  NGC4486  187.7059  12.3911
35  NGC4494  187.8502  25.7747
36  NGC4552  188.9167  12.5564
37  NGC4579  189.4312  11.8179
38  NGC4589  189.3550  74.1921
39  NGC4596  189.9840  10.1757
40  NGC4636  190.7083   2.6879
41  NGC4698  192.0957   8.4874
42  NGC4736  192.7193  41.1192
43  NGC4750  192.5303  72.8747
44  NGC4772  193.3721   2.1681
45  NGC5005  197.7346  37.0583
46  NGC5055  198.9553  42.0296
47  NGC5363  209.0307   5.2547
48  NGC5746  221.2329   1.9553
49  NGC5813  225.2972   1.7018
50  NGC5838  226.3597   2.0991
51  NGC5846  226.6224   1.6053
52  NGC5866  226.6228  55.7631
53  NGC6482  267.9539  23.0720
54  NGC7331  339.2679  34.4162
55  NGC7743  356.0893   9.9343

Ejemplo: CT_N_S = CrossTable_Nagar_Saikia

In [332]:
CT_N_S = crear_tabla(matchedE, dfN, 'Name', '_RA','_DE', dfS, 'MAIN_ID', 'RA','DEC',)
CT_N_S

     Object        RA      DEC
0   NGC2655  133.9118  78.2237
1   NGC2681  133.3860  51.3132
2   NGC2685  133.8950  58.7338
3   NGC2787  139.8287  69.2033
4   NGC2841  140.5085  50.9777
5   NGC3226  155.8628  19.8985
6   NGC3245  156.8272  28.5069
7   NGC3379  161.9573  12.5818
8   NGC3414  162.8175  27.9750
9   NGC3507  165.8561  18.1355
10  NGC3607  169.2281  18.0517
11  NGC3608  169.2461  18.1485
12  NGC3623  169.7324  13.0923
13  NGC3627  170.0628  12.9893
14  NGC3628  170.0705  13.5871
15  NGC3642  170.5743  59.0741
16  NGC3718  173.1443  53.0678
17  NGC3898  177.3145  56.0841
18  NGC3945  178.3075  60.6754
19  NGC3998  179.4848  55.4531
20  NGC4036  180.3616  61.8958
21  NGC4111  181.7628  43.0656
22  NGC4125  182.0262  65.1742
23  NGC4143  182.4008  42.5340
24  NGC4203  183.7707  33.1972
25  NGC4261  184.8469   5.8257
26  NGC4278  185.0284  29.2808
27  NGC4314  185.6335  29.8955
28  NGC4321  185.7290  15.8221
29  NGC4374  186.2656  12.8870
30  NGC4438  186.9413  13.0090
31  NGC4450  187.1235  17.0847
32  NGC4457  187.2458   3.5712
33  NGC4459  187.2505  13.9785
34  NGC4486  187.7059  12.3911
35  NGC4494  187.8502  25.7747
36  NGC4552  188.9167  12.5564
37  NGC4579  189.4312  11.8179
38  NGC4589  189.3550  74.1921
39  NGC4596  189.9840  10.1757
40  NGC4636  190.7083   2.6879
41  NGC4698  192.0957   8.4874
42  NGC4736  192.7193  41.1192
43  NGC4750  192.5303  72.8747
44  NGC4772  193.3721   2.1681
45  NGC5005  197.7346  37.0583
46  NGC5055  198.9553  42.0296
47  NGC5363  209.0307   5.2547
48  NGC5746  221.2329   1.9553
49  NGC5813  225.2972   1.7018
50  NGC5838  226.3597   2.0991
51  NGC5846  226.6224   1.6053
52  NGC5866  226.6228  55.7631
53  NGC6482  267.9539  23.0720
54  NGC7331  339.2679  34.4162
55  NGC7743  356.0893   9.9343

# Crossmatch, por coordenadas

Definimos las SkyCoord de cada catálogo

In [313]:
BRA = catalogo_Baldi['RA']
BDEC = catalogo_Baldi['DEC']
Bcoord= SkyCoord(ra= BRA, dec=BDEC, frame="icrs",unit=(u.hourangle, u.deg))


SRA = catalogo_S['RA']
SDEC = catalogo_S['DEC']
Scoord = SkyCoord(ra=SRA, dec=SDEC, frame="icrs", unit=(u.hourangle, u.deg))

LRA = laura['RA']
LDEC = laura['DEC']
Lcoord= SkyCoord(ra= LRA, dec=LDEC, frame="icrs",unit=(u.hourangle, u.deg))

NRA = catalogo_Nagar['_RA']
NDEC = catalogo_Nagar['_DE']
Ncoord= SkyCoord(ra= NRA, dec=NDEC, frame="icrs",unit=(u.deg,u.deg))

Hacemos un match entre ellos.  
idx = indice del objeto en el catalogo 2  
d2d = la distancia 2d entre ellos  
d3d = distancia 3d entre ellos.  

*¡Hace match con los cercanos! A lo mejor no es el mismo*

In [314]:
idx, d2d, d3d = Bcoord.match_to_catalog_sky(Scoord)

Entonces tenemos que añadir una condición el que exija que d2d sea 0.  
Buscamos que indice del catalogo 2 (S) lo cumple.

In [315]:
max_sep = 0*u.deg
sep_constraint = d2d == max_sep
print(idx[sep_constraint])

[  1   2   3   4   5  14  15  26  28  30  31  32  36  47  54  67  69  75
  96 108 109 110 111 112 113 114 115 116 117 119 120 121 125 132 134 137
 138 143 148 150]

Otra opción de hacer lo mismo:

In [289]:
max_sep = 0*u.deg
idxa, d2da, d3da = Bcoord.match_to_catalog_3d(Scoord)
sep_constraint = d2da == max_sep
c_matches = Bcoord[sep_constraint]
catalog_matches_coord = catalogo_S[idxa[sep_constraint]]

Imprimimos la tabla correspondiente. 
1. Índices en catalogo 2.  
2. Coordenadas en catálogo 1.  
3. Tabla

In [316]:

print('\n' 'Índices catálogo S')
print(idxa[sep_constraint])

print('\n' 'Coordenadas B')
print(c_matches.to_string('hmsdms'))

print('\n' 'Tabla con S')

catalog_matches_coord



#catalog_matches_coord.info()

Índices catálogo S
[  1   2   3   4   5  14  15  26  28  30  31  32  36  47  54  67  69  75
  96 108 109 110 111 112 113 114 115 116 117 119 120 121 125 132 134 137
 138 143 148 150]

Coordenadas B
['00h38m57.94s +48d20m15.035s', '00h42m44.33s +41d16m07.5s', '00h49m47.8149s +32d16m39.786s', '00h57m48.859s +30d21m08.842s', '01h10m58.9016s +33d09m07.053s', '02h00m14.9065s +31d25m45.85s', '02h11m17.3713s +37d29m49.713s', '06h50m08.6691s +60d50m44.864s', '08h14m40.116s +49d03m42.021s', '08h53m32.7183s +51d18m49.159s', '08h53m42.2471s +73d29m27.418s', '08h55m37.731s +78d13m23.1s', '09h22m02.6778s +50d58m35.737s', '10h51m16.2099s +27d58m30.297s', '11h26m08.5641s +43d35m09.587s', '11h58m31.417s +43d56m49.28s', '12h03m09.6101s +44d31m52.682s', '12h10m32.5759s +39d24m21.063s', '12h30m49.4233s +12d23m28.043s', '13h13m27.535s +36d35m37.14s', '13h29m52.698s +47d11m42.93s', '13h29m59.59s +47d15m58.06s', '13h31m08.2883s +30d30m32.96s', '13h42m08.3801s +35d39m15.467s', '13h46m23.694s +43d52m19.34s', '13h49m15.24s +60d11m25.8s', '13h53m26.7104s +40d16m59.2s', '13h53m26.7262s +40d18m09.928s', '13h55m39.9385s +40d27m42.38s', '13h56m16.6722s +47d14m08.568s', '13h58m37.9605s +37d25m28.161s', '14h02m50.072s +49d10m21.53s', '14h30m25.51s +35d19m15.733s', '15h06m29.561s +55d45m47.91s', '15h09m46.7271s +57d00m00.538s', '15h38m39.778s +59d21m21.21s', '15h39m37.0545s +59d19m55.216s', '17h45m40.0359s -29d00m28.169s', '18h47m18.8166s +45d33m02.274s', '20h37m14.1228s +66d06m20.049s']

Tabla con S

<Table length=40>
  MAIN_ID         RA           DEC      ...     COO_BIBCODE     SCRIPT_NUMBER_ID
               "h:m:s"       "d:m:s"    ...
   object       str13         str13     ...        object            int32
----------- ------------- ------------- ... ------------------- ----------------
  NGC   185 00 38 57.9400 +48 20 15.035 ... 2020yCat.1350....0G                1
      M  31  00 42 44.330  +41 16 07.50 ... 2006AJ....131.1163S                1
  NGC   266 00 49 47.8149 +32 16 39.786 ... 2020yCat.1350....0G                1
  NGC   315 00 57 48.8590 +30 21 08.842 ... 2020yCat.1350....0G                1
  NGC   410 01 10 58.9016 +33 09 07.053 ... 2020yCat.1350....0G                1
  NGC   777 02 00 14.9065 +31 25 45.850 ... 2020yCat.1350....0G                1
  NGC   841 02 11 17.3713 +37 29 49.713 ... 2020yCat.1350....0G                1
  NGC  2273 06 50 08.6691 +60 50 44.864 ... 2020yCat.1350....0G                1
  NGC  2541 08 14 40.1160 +49 03 42.021 ... 2020yCat.1350....0G                1
        ...           ...           ... ...                 ...              ...
  NGC  5395 13 58 37.9605 +37 25 28.161 ... 2020yCat.1350....0G                1
  NGC  5448  14 02 50.072  +49 10 21.53 ... 2006AJ....131.1163S                1
  NGC  5656 14 30 25.5100 +35 19 15.733 ... 2020yCat.1350....0G                1
      M 102  15 06 29.561  +55 45 47.91 ... 2006AJ....131.1163S                1
  NGC  5879 15 09 46.7271 +57 00 00.538 ... 2020yCat.1350....0G                1
  NGC  5982  15 38 39.778  +59 21 21.21 ... 2006AJ....131.1163S                1
  NGC  5985 15 39 37.0545 +59 19 55.216 ... 2020yCat.1350....0G                1
NAME Sgr A* 17 45 40.0359 -29 00 28.169 ... 2011AJ....142...35P                1
  NGC  6703 18 47 18.8166 +45 33 02.274 ... 2020yCat.1350....0G                1
  NGC  6951 20 37 14.1228 +66 06 20.049 ... 2020yCat.1350....0G                1

## Función general, crossmatch por coordenadas

In [322]:
def crosstable (cat1,cat2,max_sep,t1, tref,par1,par2,par3,par4,par5):
    idx, d2d, d3d = cat1.match_to_catalog_3d(cat2)
    sep_constraint = d2d == max_sep
    c1_matches = cat1[sep_constraint]
    c2_matches_coord = cat2[idx[sep_constraint]]
    t1 = tref[idx[sep_constraint]]
    t1.to_pandas()
    t1 = t1[[par1,par2,par3,par4,par5]]
    return t1

Prueba para el cruce Baldi-Saikia

In [323]:
taula =[]
tau = crosstable(Bcoord,Scoord,0*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
tau

<Table length=40>
  MAIN_ID         RA           DEC      RA_PREC DEC_PREC
               "h:m:s"       "d:m:s"
   object       str13         str13      int16   int16
----------- ------------- ------------- ------- --------
  NGC   185 00 38 57.9400 +48 20 15.035      14       14
      M  31  00 42 44.330  +41 16 07.50       7        7
  NGC   266 00 49 47.8149 +32 16 39.786      14       14
  NGC   315 00 57 48.8590 +30 21 08.842      14       14
  NGC   410 01 10 58.9016 +33 09 07.053      14       14
  NGC   777 02 00 14.9065 +31 25 45.850      14       14
  NGC   841 02 11 17.3713 +37 29 49.713      14       14
  NGC  2273 06 50 08.6691 +60 50 44.864      14       14
  NGC  2541 08 14 40.1160 +49 03 42.021      14       14
        ...           ...           ...     ...      ...
  NGC  5395 13 58 37.9605 +37 25 28.161      14       14
  NGC  5448  14 02 50.072  +49 10 21.53       7        7
  NGC  5656 14 30 25.5100 +35 19 15.733      14       14
      M 102  15 06 29.561  +55 45 47.91       7        7
  NGC  5879 15 09 46.7271 +57 00 00.538      14       14
  NGC  5982  15 38 39.778  +59 21 21.21       7        7
  NGC  5985 15 39 37.0545 +59 19 55.216      14       14
NAME Sgr A* 17 45 40.0359 -29 00 28.169       9        9
  NGC  6703 18 47 18.8166 +45 33 02.274      14       14
  NGC  6951 20 37 14.1228 +66 06 20.049      14       14