# Descarga Catálogos y crossmatch por coordenadas

In [45]:
import numpy as np
import astropy.units as u
from astropy.table import Table, QTable
from astropy.coordinates import SkyCoord
import matplotlib.pyplot as plt


from astroquery.simbad import Simbad
from astropy.coordinates import Angle

from  astroquery.gaia import Gaia
import pandas as pd

## Descarga de los catálogos de Saikia desde Vizier  

Se guardan en la carpeta "CatalogosRadio" del directorio correspondiente.    
Se leen como df.

In [46]:
from astroquery.vizier import Vizier
Vizier.ROW_LIMIT=-1

In [47]:
catalog_list = Vizier.find_catalogs('Saikia')
['{};{}'.format(k,v.description) for k,v in catalog_list.items()]

["J/ApJ/905/87;LCO i'band LC of SAX J1808.4-3658 (Baglio+, 2020)",
 'J/ApJS/238/9;Catalog of giant radio sources known to date (Kuzmicz+, 2018)',
 'J/A+A/555/A4;Radio polarimetry of CSS sources (Mantovani+ 2013)',
 'J/A+A/616/A108;Cool stars chromospheric activity catalog (Boro Saikia+, 2018)',
 'J/A+A/642/A153;SAGAN. I. New sample & multi-wavelength studies (Dabhade+, 2020)',
 'J/A+A/660/A59;SAGAN III. New insights into giant radio quasars (Mahato+, 2022)',
 'J/MNRAS/392/1403;GMRT radios sources around J0916+6348 field (Sirothia+, 2009)',
 'J/MNRAS/393/1275;STAGES master catalog (Gray+, 2009)',
 'J/MNRAS/395/269;ELAIS-N1 field 325MHz observations (Sirothia+, 2009)',
 'J/MNRAS/406/2578;Galaxies near S1189 (Mao+, 2010)',
 'J/MNRAS/414/1397;Radio study of double-double radio galaxy 3C293 (Joshi+, 2011)',
 'J/MNRAS/426/3334;Australia Telescope Large Area Survey (Mao+, 2012)',
 'J/MNRAS/435/650;325MHz GMRT survey of Herschel-ATLAS/GAMA fields (Mauch+, 2013)',
 'J/MNRAS/465/997;Low-luminosity radio-loud AGN (Chandola+, 2017)']

In [48]:
Vizier.get_catalogs('J/MNRAS/465/997')

TableList with 2 tables:
	'0:J/MNRAS/465/997/sample' with 20 column(s) and 100 row(s)
	'1:J/MNRAS/465/997/tablea3' with 15 column(s) and 100 row(s)

In [49]:
catalogo_Saikia_1 = Vizier.get_catalogs('J/MNRAS/465/997')[0]
catalogo_Saikia_2 = Vizier.get_catalogs('J/MNRAS/465/997')[1]

In [50]:
catalogo_Saikia_1.write('../CatalogosRadio/catalogo_Saikia_1.ecsv', format='ascii.ecsv', overwrite=True) 
catalogo_Saikia_2.write('../CatalogosRadio/catalogo_Saikia_2.ecsv', format='ascii.ecsv', overwrite=True)

In [51]:
catalogo_Saikia_2.to_pandas()
catalogo_Saikia_1.to_pandas()

,Samp,Seq,RAJ2000,DEJ2000,FHb,e_FHb,FO_III_,e_FO_III_,EWO_III_,e_EWO_III_,FO_I_,e_FO_I_,FHa,e_FHa,FN_II_,e_FN_II_,FS_II_,e_FS_II_,OClass,RClass
0,D,1,07 57 56.7,+39 59 36,186.261002,10.098,1364.281,20.400000,37.223999,0.360,105.588997,8.243,803.512,23.927999,691.473,16.945000,257.189,10.055,HERG,C
1,D,2,08 06 01.5,+19 06 15,46.528999,8.398,376.843,10.831000,11.258000,0.222,43.195000,6.408,336.209,17.030001,381.474,13.136000,136.350,9.655,HERG,E
2,D,3,08 09 38.9,+34 55 37,91.580002,13.851,44.482,8.970000,1.059000,0.134,18.584000,7.407,114.215,21.062000,132.103,15.357000,34.271,10.370,LERG,E
3,D,4,08 36 37.8,+44 01 10,141.160995,11.989,915.593,17.146999,23.732000,0.282,114.595001,9.000,528.403,26.059999,632.954,20.318001,254.389,13.003,HERG,C
4,D,5,08 43 07.1,+45 37 43,6.874000,4.445,6.719,4.618000,0.908000,0.462,1.435000,3.411,28.736,13.966000,29.787,10.209000,2.635,5.381,LERG,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,N,96,16 06 16.0,+18 15 00,111.921997,23.497,143.126,18.211000,1.112000,0.096,77.808998,19.253,221.277,51.681000,508.542,41.967999,126.840,25.462,LERG,E
96,N,97,16 08 21.1,+28 28 43,114.061996,13.898,125.271,11.665000,2.287000,0.167,88.045998,10.349,348.333,26.242001,321.418,19.187000,140.174,13.342,LERG,E
97,N,98,16 14 19.6,+50 27 56,139.589005,15.976,322.690,15.814000,5.883000,0.196,169.921005,13.174,492.155,33.883999,650.159,27.299000,319.541,18.491,LERG,E
98,N,99,16 15 41.2,+47 11 12,60.546001,11.150,23.222,5.865000,1.006000,0.186,14.360000,4.810,97.552,17.084999,60.455,10.647000,16.506,6.894,LERG,E
99,N,100,16 24 24.5,+48 31 42,123.108002,13.175,140.341,11.324000,2.483000,0.144,76.103996,10.707,377.411,28.131001,507.570,22.709000,238.491,15.361,LERG,C

Descargamos otro catálogo en Simbad.

In [52]:
catalogo_S = Simbad.query_bibobj('2018A&A...616A.152S')

In [53]:
catalogo_S.to_pandas()

,MAIN_ID,RA,DEC,RA_PREC,DEC_PREC,COO_ERR_MAJA,COO_ERR_MINA,COO_ERR_ANGLE,COO_QUAL,COO_WAVELENGTH,COO_BIBCODE,SCRIPT_NUMBER_ID
0,NGC 7814,00 03 14.947,+16 08 42.82,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
1,NGC 185,00 38 57.9400,+48 20 15.035,14,14,25.095501,7.0605,90,C,O,2020yCat.1350....0G,1
2,M 31,00 42 44.330,+41 16 07.50,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
3,NGC 266,00 49 47.8149,+32 16 39.786,14,14,0.824800,0.3663,90,C,O,2020yCat.1350....0G,1
4,NGC 315,00 57 48.8590,+30 21 08.842,14,14,17.628700,12.0649,90,C,O,2020yCat.1350....0G,1
...,...,...,...,...,...,...,...,...,...,...,...,...
149,V* V404 Cyg,20 24 03.8254,+33 52 01.962,14,14,0.073300,0.0886,90,A,O,2018yCat.1345....0G,1
150,NGC 6951,20 37 14.1228,+66 06 20.049,14,14,0.470900,0.5494,90,A,O,2020yCat.1350....0G,1
151,NGC 7479,23 04 56.6432,+12 19 22.357,14,14,13.757400,11.3832,90,C,O,2020yCat.1350....0G,1
152,NGC 7626,23 20 42.524,+08 13 01.43,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
153,NGC 7743,23 44 21.1607,+09 56 02.970,14,14,0.343300,0.2436,90,A,O,2020yCat.1350....0G,1

## Lectura del catálogo de Laura
Se lee desde el directorio (descarga previa desde Drive).  
Se convierte en df.

In [54]:
laura = Table.read('../CatalogosRadio/Laura.csv') #Leer tabla
laura.to_pandas()

      Objeto            RA           DEC Redshift Magnitud (V)
0   NGC 0266   00 49 47.80   +32 16 39.8   0,0155        11,82
1   NGC 0315   00 57 48.88   +30 21 08.8   0,0165         11,6
2   NGC 0410  01 10 58.904  +33 09 06.81   0,0177        11,48
3   NGC 0474   01 20 06.70   +03 24 55.0   0,0077        11,52
4   NGC 0524   01 24 47.72     +09 32 20    0,008        10,35
..       ...           ...           ...      ...          ...
70  NGC 6482   17 51 48.81   +23 04 19.0   0,0131        11,33
71  NGC 7285   22 28 38.00   −24 50 26.8   0,0144           --
72  NGC 7331   22 37 04.09   +34 24 56.3   0,0038         9,41
73   IC 1459   22 57 10.60   −36 27 44.0   0,0055        10,54
74  NGC 7743   23 44 21.14   +09 56 02.7   0,0057        12,43

[75 rows x 5 columns]

## Descarga de los catálogos de Baldi desde Simbad

Se guardan en la carpeta "CatalogosRadio" del directorio correspondiente.    
Se leen como df.

In [55]:
limitedSimbad = Simbad()

limitedSimbad.ROW_LIMIT = 6

In [56]:
catalogo_Baldi = Simbad.query_bibobj('2018MNRAS.476.3478B')

In [57]:
catalogo_Baldi.write('../CatalogosRadio/catalogo_Baldi.ecsv', format='ascii.ecsv', overwrite=True)

In [58]:
catalogo_Baldi.to_pandas()

,MAIN_ID,RA,DEC,RA_PREC,DEC_PREC,COO_ERR_MAJA,COO_ERR_MINA,COO_ERR_ANGLE,COO_QUAL,COO_WAVELENGTH,COO_BIBCODE,SCRIPT_NUMBER_ID
0,NGC 7817,00 03 58.899,+20 45 08.42,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
1,IC 10,00 20 23.16,+59 17 34.7,6,6,10800.000000,10800.0000,90,D,,1999ApJS..125..409C,1
2,NGC 147,00 33 12.120,+48 30 31.46,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
3,NGC 185,00 38 57.9400,+48 20 15.035,14,14,25.095501,7.0605,90,C,O,2020yCat.1350....0G,1
4,NGC 189,00 39 32,+61 05.4,4,4,NaN,NaN,0,D,O,2020A&A...633A..99C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
120,NGC 7332,22 37 24.5373,+23 47 53.830,14,14,0.292300,0.3253,90,A,O,2020yCat.1350....0G,1
121,NGC 7457,23 00 59.9263,+30 08 41.764,14,14,0.104700,0.1328,90,A,O,2020yCat.1350....0G,1
122,NGC 7640,23 22 06.5746,+40 50 43.114,14,14,3.167100,7.1131,90,C,O,2020yCat.1350....0G,1
123,NGC 7741,23 43 54.375,+26 04 32.07,7,7,NaN,NaN,0,C,I,2006AJ....131.1163S,1
124,NGC 7798,23 59 25.5026,+20 44 59.355,14,14,3.944400,2.4878,90,C,O,2018yCat.1345....0G,1

Nagar

In [59]:
catalog_list = Vizier.find_catalogs('Nagar')
['{};{}'.format(k,v.description) for k,v in catalog_list.items()]

['J/ApJ/807/150;230GHz VLBI observations of M87 (Akiyama+, 2015)',
 'J/ApJ/859/60;Sgr A* 1.3mm VLBI observations with the EHT in 2013 (Lu+, 2018)',
 'J/ApJ/879/10;2015-2017 LIGO obs. analysis for 221 pulsars (Abbott+, 2019)',
 'J/A+A/409/115;VLA imaging of IRAS 1 Jy ULIRG sample (Nagar+, 2003)',
 'J/A+A/435/521;Radio Sources in Low-Luminosity AGNs. IV (Nagar+, 2005)',
 'J/A+A/597/A41;ALMA Frontier Fields Survey. I. (Gonzalez-Lopez+, 2017)',
 'J/A+A/621/A83;NGC 1566 ALMA and Gemini-GMOS/IFU datacubes (Slater+, 2019)',
 'J/A+A/633/A127;Jet-driven outflow in ESO 420-G13 (Fernandez-Ontiveros+, 2020)',
 'J/A+A/640/A69;3C 279 Event Horizon Telescope imaging (Kim+, 2020)',
 'J/AJ/120/1364;Abundances in M3 and M13 (Cavallo+, 2000)']

In [60]:
Vizier.get_catalogs('J/A+A/435/521')

TableList with 3 tables:
	'0:J/A+A/435/521/table1' with 15 column(s) and 197 row(s)
	'1:J/A+A/435/521/table2' with 15 column(s) and 44 row(s)
	'2:J/A+A/435/521/notes' with 2 column(s) and 35 row(s)

In [61]:
catalogo_Nagar = Vizier.get_catalogs('J/A+A/435/521')[0]

In [62]:
catalogo_Nagar.write('../CatalogosRadio/catalogo_Nagar.ecsv', format='ascii.ecsv', overwrite=True)

In [85]:
catalogo_Nagar.to_pandas()

,Name,AType,TType,Dist,Delta,Sp15GHz,l_St15GHz,St15GHz,l_Lp15GHz,Lp15GHz,Note,Simbad,NED,_RA,_DE
0,IC239,L2::,6.0,16.799999,NaN,NaN,<,0.9,<,19.480000,<NA>,Simbad,NED,39.1163,38.9690
1,IC356,T2,2.0,18.100000,NaN,NaN,<,1.0,<,19.590000,4,Simbad,NED,61.9436,69.8126
2,IC520,T2:,2.0,47.000000,NaN,NaN,<,1.0,<,20.420000,4,Simbad,NED,133.4258,73.4908
3,IC1727,T2/L2,9.0,8.200000,NaN,NaN,<,0.9,<,18.860001,<NA>,Simbad,NED,26.8748,27.3330
4,NGC185,S2,-5.0,0.700000,NaN,NaN,<,1.1,<,16.809999,<NA>,Simbad,NED,9.7392,48.3373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,NGC7479,S1.9,5.0,32.400002,1.0,2.400000,,2.5,,20.480000,<NA>,Simbad,NED,346.2362,12.3231
193,NGC7626,L2::,-5.0,45.599998,2.9,39.799999,,40.0,,22.000000,<NA>,Simbad,NED,350.1778,8.2164
194,NGC7742,T2/L2,3.0,22.200001,NaN,NaN,<,1.1,<,19.809999,<NA>,Simbad,NED,356.0661,10.7669
195,NGC7743,S2,-1.0,24.400000,1.1,1.000000,,1.5,,19.850000,<NA>,Simbad,NED,356.0893,9.9343
196,NGC7814,L2::,2.0,15.100000,NaN,NaN,<,1.1,<,19.480000,<NA>,Simbad,NED,0.8121,16.1454

# Crossmatch, por coordenadas

Definimos las SkyCoord de cada catalogo y hacemos un match entre ellos.  
idx = indice del objeto en el catalogo 2  
d2d = la distancia 2d entre ellos  
d3d = distancia 3d entre ellos.  

*¡Hace match con los cercanos! A lo mejor no es el mismo*

In [167]:
BRA = catalogo_Baldi['RA']
BDEC = catalogo_Baldi['DEC']
Bcoord= SkyCoord(ra= BRA, dec=BDEC, frame="icrs",unit=(u.hourangle, u.deg))


SRA = catalogo_S['RA']
SDEC = catalogo_S['DEC']
Scoord = SkyCoord(ra=SRA, dec=SDEC, frame="icrs", unit=(u.hourangle, u.deg))

LRA = laura['RA']
LDEC = laura['DEC']
Lcoord= SkyCoord(ra= LRA, dec=LDEC, frame="icrs",unit=(u.hourangle, u.deg))

NRA = catalogo_Nagar['_RA']
NDEC = catalogo_Nagar['_DE']
Ncoord= SkyCoord(ra= NRA, dec=NDEC, frame="icrs",unit=(u.deg,u.deg))

In [169]:
idx, d2d, d3d = Bcoord.match_to_catalog_sky(Scoord)

Entonces tenemos que añadir una condición el que exija que d2d sea 0.  
Buscamos que indice del catalogo 2 (S) lo cumple.

In [170]:
max_sep = 0*u.deg
sep_constraint = d2d == max_sep
print(idx[sep_constraint])

[  1   2   3   4   5  14  15  26  28  30  31  32  36  47  54  67  69  75
  96 108 109 110 111 112 113 114 115 116 117 119 120 121 125 132 134 137
 138 143 148 150]

Otra opción de hacer lo mismo

In [171]:
max_sep = 0*u.deg
idxa, d2da, d3da = Bcoord.match_to_catalog_3d(Scoord)
sep_constraint = d2da == max_sep
c_matches = Bcoord[sep_constraint]
catalog_matches_coord = catalogo_S[idxa[sep_constraint]]

Imprimimos la tabla correspondiente.  
1. Índices en catalogo 2.  
2. Coordenadas en catálogo 1.  
3. Tabla

In [172]:
print('\n' 'Índices catálogo S')
print(idxa[sep_constraint])

print('\n' 'Coordenadas B')
print(c_matches.to_string('hmsdms'))

print('\n' 'Tabla con S')

catalog_matches_coord



#catalog_matches_coord.info()

Índices catálogo S
[  1   2   3   4   5  14  15  26  28  30  31  32  36  47  54  67  69  75
  96 108 109 110 111 112 113 114 115 116 117 119 120 121 125 132 134 137
 138 143 148 150]

Coordenadas B
['00h38m57.94s +48d20m15.035s', '00h42m44.33s +41d16m07.5s', '00h49m47.8149s +32d16m39.786s', '00h57m48.859s +30d21m08.842s', '01h10m58.9016s +33d09m07.053s', '02h00m14.9065s +31d25m45.85s', '02h11m17.3713s +37d29m49.713s', '06h50m08.6691s +60d50m44.864s', '08h14m40.116s +49d03m42.021s', '08h53m32.7183s +51d18m49.159s', '08h53m42.2471s +73d29m27.418s', '08h55m37.731s +78d13m23.1s', '09h22m02.6778s +50d58m35.737s', '10h51m16.2099s +27d58m30.297s', '11h26m08.5641s +43d35m09.587s', '11h58m31.417s +43d56m49.28s', '12h03m09.6101s +44d31m52.682s', '12h10m32.5759s +39d24m21.063s', '12h30m49.4233s +12d23m28.043s', '13h13m27.535s +36d35m37.14s', '13h29m52.698s +47d11m42.93s', '13h29m59.59s +47d15m58.06s', '13h31m08.2883s +30d30m32.96s', '13h42m08.3801s +35d39m15.467s', '13h46m23.694s +43d52m19.34s', '13h49m15.24s +60d11m25.8s', '13h53m26.7104s +40d16m59.2s', '13h53m26.7262s +40d18m09.928s', '13h55m39.9385s +40d27m42.38s', '13h56m16.6722s +47d14m08.568s', '13h58m37.9605s +37d25m28.161s', '14h02m50.072s +49d10m21.53s', '14h30m25.51s +35d19m15.733s', '15h06m29.561s +55d45m47.91s', '15h09m46.7271s +57d00m00.538s', '15h38m39.778s +59d21m21.21s', '15h39m37.0545s +59d19m55.216s', '17h45m40.0359s -29d00m28.169s', '18h47m18.8166s +45d33m02.274s', '20h37m14.1228s +66d06m20.049s']

Tabla con S

<Table length=40>
  MAIN_ID         RA           DEC      ...     COO_BIBCODE     SCRIPT_NUMBER_ID
               "h:m:s"       "d:m:s"    ...
   object       str13         str13     ...        object            int32
----------- ------------- ------------- ... ------------------- ----------------
  NGC   185 00 38 57.9400 +48 20 15.035 ... 2020yCat.1350....0G                1
      M  31  00 42 44.330  +41 16 07.50 ... 2006AJ....131.1163S                1
  NGC   266 00 49 47.8149 +32 16 39.786 ... 2020yCat.1350....0G                1
  NGC   315 00 57 48.8590 +30 21 08.842 ... 2020yCat.1350....0G                1
  NGC   410 01 10 58.9016 +33 09 07.053 ... 2020yCat.1350....0G                1
  NGC   777 02 00 14.9065 +31 25 45.850 ... 2020yCat.1350....0G                1
  NGC   841 02 11 17.3713 +37 29 49.713 ... 2020yCat.1350....0G                1
  NGC  2273 06 50 08.6691 +60 50 44.864 ... 2020yCat.1350....0G                1
  NGC  2541 08 14 40.1160 +49 03 42.021 ... 2020yCat.1350....0G                1
        ...           ...           ... ...                 ...              ...
  NGC  5395 13 58 37.9605 +37 25 28.161 ... 2020yCat.1350....0G                1
  NGC  5448  14 02 50.072  +49 10 21.53 ... 2006AJ....131.1163S                1
  NGC  5656 14 30 25.5100 +35 19 15.733 ... 2020yCat.1350....0G                1
      M 102  15 06 29.561  +55 45 47.91 ... 2006AJ....131.1163S                1
  NGC  5879 15 09 46.7271 +57 00 00.538 ... 2020yCat.1350....0G                1
  NGC  5982  15 38 39.778  +59 21 21.21 ... 2006AJ....131.1163S                1
  NGC  5985 15 39 37.0545 +59 19 55.216 ... 2020yCat.1350....0G                1
NAME Sgr A* 17 45 40.0359 -29 00 28.169 ... 2011AJ....142...35P                1
  NGC  6703 18 47 18.8166 +45 33 02.274 ... 2020yCat.1350....0G                1
  NGC  6951 20 37 14.1228 +66 06 20.049 ... 2020yCat.1350....0G                1

# Función final

Funcion: Crear una tabla con los objetos coincidentes(en coordenadas) entre dos catálogos.  
Parámetros:  
    - SkyCoord catálogo 1 (input)  
    - SkyCoord catálogo 2 (input)  
    - Máxima separación (input)  
    - Tabla de salida (input/output)  
    - Catálogo de referencia (input)
    - 5 parametros: columnas en la tabla, segun su nombre en el catálogo de referencia

In [194]:
def crosstable (cat1,cat2,max_sep,t1,tabref,par1,par2,par3,par4,par5):
    idx, d2d, d3d = cat1.match_to_catalog_3d(cat2)
    sep_constraint = d2d < max_sep
    c1_matches = cat1[sep_constraint]
    c2_matches_coord = cat2[idx[sep_constraint]]
    t1 = tabref[idx[sep_constraint]]
    t1.to_pandas()
    t1 = t1[[par1,par2,par3,par4,par5]]
    return t1

## Crossmatches:

Baldi-Saikia

In [206]:
taula =[]
tau = crosstable(Bcoord,Scoord,0.0001*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
tau

<Table length=40>
  MAIN_ID         RA           DEC      RA_PREC DEC_PREC
               "h:m:s"       "d:m:s"
   object       str13         str13      int16   int16
----------- ------------- ------------- ------- --------
  NGC   185 00 38 57.9400 +48 20 15.035      14       14
      M  31  00 42 44.330  +41 16 07.50       7        7
  NGC   266 00 49 47.8149 +32 16 39.786      14       14
  NGC   315 00 57 48.8590 +30 21 08.842      14       14
  NGC   410 01 10 58.9016 +33 09 07.053      14       14
  NGC   777 02 00 14.9065 +31 25 45.850      14       14
  NGC   841 02 11 17.3713 +37 29 49.713      14       14
  NGC  2273 06 50 08.6691 +60 50 44.864      14       14
  NGC  2541 08 14 40.1160 +49 03 42.021      14       14
        ...           ...           ...     ...      ...
  NGC  5395 13 58 37.9605 +37 25 28.161      14       14
  NGC  5448  14 02 50.072  +49 10 21.53       7        7
  NGC  5656 14 30 25.5100 +35 19 15.733      14       14
      M 102  15 06 29.561  +55 45 47.91       7        7
  NGC  5879 15 09 46.7271 +57 00 00.538      14       14
  NGC  5982  15 38 39.778  +59 21 21.21       7        7
  NGC  5985 15 39 37.0545 +59 19 55.216      14       14
NAME Sgr A* 17 45 40.0359 -29 00 28.169       9        9
  NGC  6703 18 47 18.8166 +45 33 02.274      14       14
  NGC  6951 20 37 14.1228 +66 06 20.049      14       14

Laura-Saikia

In [229]:
taula=[]
CT_L_S = crosstable(Lcoord,Scoord,0.0001*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')

CT_L_S

<Table length=27>
         MAIN_ID                RA           DEC      RA_PREC DEC_PREC
                             "h:m:s"       "d:m:s"
          object              str13         str13      int16   int16
------------------------- ------------- ------------- ------- --------
                NGC   266 00 49 47.8149 +32 16 39.786      14       14
                NGC   315 00 57 48.8590 +30 21 08.842      14       14
                NGC   410 01 10 58.9016 +33 09 07.053      14       14
                NGC   841 02 11 17.3713 +37 29 49.713      14       14
                NGC  2655  08 55 37.731  +78 13 23.10       7        7
                NGC  2681 08 53 32.7183 +51 18 49.159      14       14
                NGC  3226 10 23 27.0064 +19 53 54.674      14       14
                NGC  3414 10 51 16.2099 +27 58 30.297      14       14
[VV2006] J111654.8+180304  11 16 54.657  +18 03 06.51       7        7
                      ...           ...           ...     ...      ...
                NGC  4278 12 20 06.8253 +29 16 50.713      11       11
                    M  84 12 25 03.7433 +12 53 13.139       9        9
                    M  87 12 30 49.4233 +12 23 28.043      12       12
                    M  89 12 35 39.8073 +12 33 22.830      11       11
                NGC  4589 12 37 24.9947 +74 11 30.861      14       14
                NGC  4750 12 50 07.3113 +72 52 28.653      14       14
                NGC  4772 12 53 29.1636 +02 10 06.146      14       14
                NGC  5813 15 01 11.2302 +01 42 07.141      14       14
                NGC  5838 15 05 26.2447 +02 05 57.349      14       14
                NGC  6482 17 51 48.8339 +23 04 18.889      14       14

Laura-Nagar

In [208]:
taula=[]
CT_L_N = crosstable(Lcoord,Ncoord,0.0001*u.deg,taula,catalogo_Nagar,'Name','_RA','_DE','Dist','Delta')
CT_L_N

<Table length=6>
  Name    _RA      _DE      Dist   Delta
          deg      deg      Mpc    arcsec
  str7  float64  float64  float32 float32
------- -------- -------- ------- -------
 NGC315  14.4537  30.3524    65.8      --
NGC4036 180.3616  61.8958    24.6     2.6
NGC4278 185.0284  29.2808     9.7     1.7
NGC4374 186.2656  12.8870    16.8     3.2
NGC4486 187.7059  12.3911    16.8     3.1
NGC4750 192.5303  72.8747    26.1      --

Laura-Baldi

In [219]:
taula=[]
CT_L_B = crosstable(Lcoord,Bcoord,0.0001*u.deg,taula,catalogo_Baldi,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
CT_L_B

<Table length=10>
 MAIN_ID        RA           DEC      RA_PREC DEC_PREC
             "h:m:s"       "d:m:s"
  object      str13         str13      int16   int16
--------- ------------- ------------- ------- --------
NGC   266 00 49 47.8149 +32 16 39.786      14       14
NGC   315 00 57 48.8590 +30 21 08.842      14       14
NGC   410 01 10 58.9016 +33 09 07.053      14       14
NGC   841 02 11 17.3713 +37 29 49.713      14       14
NGC  2639 08 43 38.0682 +50 12 19.942      14       14
NGC  2655  08 55 37.731  +78 13 23.10       7        7
NGC  2681 08 53 32.7183 +51 18 49.159      14       14
NGC  2685 08 55 34.7027 +58 44 03.876      14       14
NGC  3414 10 51 16.2099 +27 58 30.297      14       14
    M  87 12 30 49.4233 +12 23 28.043      12       12

Baldi-Saikia

In [210]:
taula=[]
CT_L_B = crosstable(Bcoord,Scoord,0.0001*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
CT_L_B

<Table length=40>
  MAIN_ID         RA           DEC      RA_PREC DEC_PREC
               "h:m:s"       "d:m:s"
   object       str13         str13      int16   int16
----------- ------------- ------------- ------- --------
  NGC   185 00 38 57.9400 +48 20 15.035      14       14
      M  31  00 42 44.330  +41 16 07.50       7        7
  NGC   266 00 49 47.8149 +32 16 39.786      14       14
  NGC   315 00 57 48.8590 +30 21 08.842      14       14
  NGC   410 01 10 58.9016 +33 09 07.053      14       14
  NGC   777 02 00 14.9065 +31 25 45.850      14       14
  NGC   841 02 11 17.3713 +37 29 49.713      14       14
  NGC  2273 06 50 08.6691 +60 50 44.864      14       14
  NGC  2541 08 14 40.1160 +49 03 42.021      14       14
        ...           ...           ...     ...      ...
  NGC  5395 13 58 37.9605 +37 25 28.161      14       14
  NGC  5448  14 02 50.072  +49 10 21.53       7        7
  NGC  5656 14 30 25.5100 +35 19 15.733      14       14
      M 102  15 06 29.561  +55 45 47.91       7        7
  NGC  5879 15 09 46.7271 +57 00 00.538      14       14
  NGC  5982  15 38 39.778  +59 21 21.21       7        7
  NGC  5985 15 39 37.0545 +59 19 55.216      14       14
NAME Sgr A* 17 45 40.0359 -29 00 28.169       9        9
  NGC  6703 18 47 18.8166 +45 33 02.274      14       14
  NGC  6951 20 37 14.1228 +66 06 20.049      14       14

Nagar-Saikia

In [205]:
taula=[]
CT_N_S = crosstable(Ncoord,Scoord,0.0001*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
CT_N_S

<Table length=13>
 MAIN_ID        RA           DEC      RA_PREC DEC_PREC
             "h:m:s"       "d:m:s"
  object      str13         str13      int16   int16
--------- ------------- ------------- ------- --------
NGC   521 01 24 33.7729 +01 43 52.911      14       14
   3C  84 03 19 48.1599 +41 30 42.108      14       14
    M  81 09 55 33.1726 +69 03 55.062      14       14
NGC  3414 10 51 16.2099 +27 58 30.297      14       14
NGC  4036 12 01 26.7603 +61 53 44.625      14       14
NGC  4051 12 03 09.6101 +44 31 52.682      14       14
NGC  4278 12 20 06.8253 +29 16 50.713      11       11
NGC  4314 12 22 32.0223 +29 53 43.814      14       14
    M  84 12 25 03.7433 +12 53 13.139       9        9
    M  87 12 30 49.4233 +12 23 28.043      12       12
NGC  4750 12 50 07.3113 +72 52 28.653      14       14
NGC  5322   13 49 15.24   +60 11 25.8       6        6
NGC  6500 17 55 59.7825 +18 20 17.642      14       14

Nagar-Saikia

In [228]:
taula=[]
CT_N_B = crosstable(Ncoord,Scoord,0.0005*u.deg,taula,catalogo_S,'MAIN_ID','RA','DEC','RA_PREC','DEC_PREC')
CT_N_B

<Table length=84>
 MAIN_ID        RA           DEC      RA_PREC DEC_PREC
             "h:m:s"       "d:m:s"
  object      str13         str13      int16   int16
--------- ------------- ------------- ------- --------
  IC  239 02 36 27.8262 +38 58 09.083      14       14
  IC  520 08 53 42.2471 +73 29 27.418      14       14
NGC   315 00 57 48.8590 +30 21 08.842      14       14
NGC   410 01 10 58.9016 +33 09 07.053      14       14
NGC   474 01 20 06.6870 +03 24 55.861      14       14
NGC   521 01 24 33.7729 +01 43 52.911      14       14
NGC   718 01 53 13.2842 +04 11 44.843      14       14
NGC   777 02 00 14.9065 +31 25 45.850      14       14
NGC   841 02 11 17.3713 +37 29 49.713      14       14
      ...           ...           ...     ...      ...
    M 102  15 06 29.561  +55 45 47.91       7        7
NGC  5982  15 38 39.778  +59 21 21.21       7        7
NGC  6340 17 10 24.8346 +72 18 15.919      14       14
NGC  6482 17 51 48.8339 +23 04 18.889      14       14
NGC  6500 17 55 59.7825 +18 20 17.642      14       14
NGC  6503 17 49 26.4207 +70 08 39.604      14       14
NGC  6703 18 47 18.8166 +45 33 02.274      14       14
NGC  6951 20 37 14.1228 +66 06 20.049      14       14
NGC  7479 23 04 56.6432 +12 19 22.357      14       14
NGC  7814  00 03 14.947  +16 08 42.82       7        7